##Use this file to design rules for how to automatically set default protocol for a grid.
- conditions:
    - [holeType.name, NegativeStain]
    - [holeType.name, Lacey]
  mode: any
  protocol: NegativeStain
- conditions:
    - [params_id.bis_max_distance, 0]
    - [params_id.tilt_angle, '!__0']
  mode: any
  protocol: SPA
- conditions:
    - [holeType.hole_size, '!__None']
    - [params_id.bis_max_distance, '!__0']
    - [params_id.tilt_angle, 0]
  mode: all
  protocol: SPA-Ptolemy